language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec danger
    - rvm: 2.3.1
      env: DATABASE_ADAPTER=activerecord
      services:
        - postgresql
    - rvm: 2.3.1
      env: DATABASE_ADAPTER=mongoid
      services:
        - mongodb

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

